#!/usr/bin/env bash
# dump-schema.sh — Export full SQLite schema to docs/SCHEMA.md
# Run from project root or as a plugin (CLAUDE_PLUGIN_ROOT set automatically)

set -euo pipefail

ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
DB="$ROOT/data/soy.db"
OUT="$ROOT/docs/SCHEMA.md"
INCLUDE_SAMPLES="${1:-}"  # pass "samples" to include sample data rows

if [ ! -f "$DB" ]; then
  echo "Error: Database not found at $DB" >&2
  echo "Run bootstrap first: bash shared/bootstrap.sh" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

{
  echo "# Software of You — Database Schema"
  echo ""
  echo "> Auto-generated by \`scripts/dump-schema.sh\` on $(date '+%Y-%m-%d %H:%M')"
  echo "> Database: \`~/.local/share/software-of-you/soy.db\`"
  echo ""
  echo "---"
  echo ""

  # --- Tables ---
  tables=$(sqlite3 "$DB" "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;")

  echo "## Tables"
  echo ""
  echo "| Table | Rows | Description |"
  echo "|-------|------|-------------|"
  for t in $tables; do
    count=$(sqlite3 "$DB" "SELECT COUNT(*) FROM \"$t\";")
    echo "| [$t](#$t) | $count | |"
  done
  echo ""

  for t in $tables; do
    echo "---"
    echo ""
    echo "### $t"
    echo ""

    # Column info
    echo "| Column | Type | Nullable | Default | Constraints |"
    echo "|--------|------|----------|---------|-------------|"

    sqlite3 -separator '|' "$DB" "PRAGMA table_info(\"$t\");" | while IFS='|' read -r cid col_name col_type notnull dflt pk; do
      nullable="YES"
      [ "$notnull" = "1" ] && nullable="NO"
      constraints=""
      [ "$pk" = "1" ] && constraints="PRIMARY KEY"
      dflt_display="${dflt:-}"
      echo "| \`$col_name\` | $col_type | $nullable | $dflt_display | $constraints |"
    done

    echo ""

    # Foreign keys
    fks=$(sqlite3 -separator '|' "$DB" "PRAGMA foreign_key_list(\"$t\");" 2>/dev/null || true)
    if [ -n "$fks" ]; then
      echo "**Foreign keys:**"
      echo "$fks" | while IFS='|' read -r _id _seq fk_table from_col to_col _on_update on_delete _match; do
        echo "- \`$from_col\` -> \`$fk_table($to_col)\` ON DELETE $on_delete"
      done
      echo ""
    fi

    # CHECK constraints — extract with balanced parens via awk
    check_sql=$(sqlite3 "$DB" "SELECT sql FROM sqlite_master WHERE type='table' AND name='$t';" 2>/dev/null || true)
    checks=$(echo "$check_sql" | tr '\n' ' ' | awk '{
      s = $0
      while (match(s, /CHECK *\(/)) {
        s = substr(s, RSTART)
        depth = 0; i = 1
        while (i <= length(s)) {
          c = substr(s, i, 1)
          if (c == "(") depth++
          if (c == ")") { depth--; if (depth == 0) break }
          i++
        }
        print substr(s, 1, i)
        s = substr(s, i + 1)
      }
    }' 2>/dev/null || true)
    if [ -n "$checks" ]; then
      echo "**Check constraints:**"
      echo "$checks" | while read -r ck; do
        echo "- \`$ck\`"
      done
      echo ""
    fi

    # Row count and optional sample data
    row_count=$(sqlite3 "$DB" "SELECT COUNT(*) FROM \"$t\";")
    if [ "$row_count" -gt 0 ]; then
      if [ "$INCLUDE_SAMPLES" = "samples" ]; then
        echo "<details>"
        echo "<summary>Sample data ($row_count rows total)</summary>"
        echo ""
        echo '```'
        sqlite3 -header -column "$DB" "SELECT * FROM \"$t\" LIMIT 3;"
        echo '```'
        echo ""
        echo "</details>"
      else
        echo "Row count: **$row_count**"
      fi
    else
      echo "*No data yet.*"
    fi
    echo ""
  done

  # --- Views ---
  views=$(sqlite3 "$DB" "SELECT name FROM sqlite_master WHERE type='view' ORDER BY name;")

  if [ -n "$views" ]; then
    echo "---"
    echo ""
    echo "## Computed Views"
    echo ""
    echo "These views pre-compute common queries. **Always prefer views over ad-hoc JOINs.**"
    echo ""

    for v in $views; do
      echo "### $v"
      echo ""

      # Extract column names from the view comment (SQLite appends /* cols */ to views)
      view_sql=$(sqlite3 "$DB" "SELECT sql FROM sqlite_master WHERE type='view' AND name='$v';")
      cols=$(echo "$view_sql" | grep -oE '/\* [^*]+ \*/' 2>/dev/null | sed 's|/\* ||;s| \*/||' | tr ',' '\n' | sed 's/^ //' || true)

      if [ -n "$cols" ]; then
        echo "**Columns:** \`$(echo "$cols" | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')\`"
      fi
      echo ""

      # Row count and optional sample data
      v_count=$(sqlite3 "$DB" "SELECT COUNT(*) FROM \"$v\";" 2>/dev/null || echo "0")
      if [ "$v_count" -gt 0 ]; then
        if [ "$INCLUDE_SAMPLES" = "samples" ]; then
          echo "<details>"
          echo "<summary>Sample data ($v_count rows)</summary>"
          echo ""
          echo '```'
          sqlite3 -header -column "$DB" "SELECT * FROM \"$v\" LIMIT 3;" 2>/dev/null || echo "(query failed)"
          echo '```'
          echo ""
          echo "</details>"
        else
          echo "Row count: **$v_count**"
        fi
      else
        echo "*No data.*"
      fi
      echo ""
    done
  fi

} > "$OUT"

echo "Schema exported to $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
